baseURL = 'https://scene-ephemere.github.io/'
languageCode = 'fr-be'
title = 'Scène-Ephémère'
theme = 'pehtheme'
publishDir = "../generated/"

paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
# #googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
# #disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'
    enableDarkMode = true
    defaultDarkMode = true


[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Poulpes Fiction'
		pageRef = '/poulpes-fiction'
		weight = 15        
        [menu.main.params]
            image='../images/poulpes-fiction/logo.png'

	[[menu.main]]
		name = 'Shows'
		pageRef = '/categories/shows'
		weight = 25
	[[menu.main]]
		name = 'Taxonomy'
		pageRef = '/tags/space/'
		weight = 30

    [[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'